pipeline {
    agent {
        docker { image 'node:16.15-alpine' }
    }
    
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}