version: "3"
services:
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
    volumes:
      - "/home/warteruzannan/Workspace/pegaki/jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
